<?xml version="1.0" encoding="utf-8"?>
<!-- COLLEGO UNA DTD INTERNA / Я соединила одну внутреннюю DTD-->
<!DOCTYPE TEI [
    <!ELEMENT TEI (header, facsimile?, text+)>
    <!ELEMENT header (#PCDATA)>
    <!ELEMENT facsimile (#PCDATA)>
    <!ELEMENT testo (#PCDATA|seg)*>

    <!ATTLIST header
        type CDATA #FIXED "intestazione" 
        lang NMTOKEN #IMPLIED>

    <!ATTLIST facsimile
        source CDATA #REQUIRED
        ref IDREFS #IMPLIED>

    <!ATTLIST testo
        id ID #REQUIRED
        type CDATA #IMPLIED>
]>

<!--Задание ESERCIZIO
    
    root: TEI
    Figli:
        - header(obbligatorio una volta sola)
        - facsimile(opzionale una volta sola)
        - testo(obbligatorio una o più volte)
        * testo è un mixed content con possibile elemento <seg>
    Attributi:
    - header: type:(fixed, CDATA "intestazione"); lang(opzionale, NMTOKEN)
    - facsimile: source:(obbligatorio); ref(optionale, IDREFS)
    - testo: id(obbligatorio, ID) type(opzionale contenuto testuale)
-->

<!-- XML -->
<TEI>
    <header type="intestazione" lang="IT">
        bla bla bla 
    </header>

    <facsimile source="rappresentazione" ref="t1">
        bla bla bla
    </facsimile>

    <testo id="t1" type="contenuto testuale">
        BLA BLA BLA senza seg
    </testo>

    <testo id="t2" type="tag"> 
        <seg>
            tag seg
        </seg>
    </testo>
</TEI>

<!--studentessa: Evgeniia Anikeeva 
    matricola: 559261
    corso: codifica di testi 19-20-->
